ls:
  .ts: regex:([A-Za-z0-9]*)([-.][A-Za-z0-9]+)*
  .tsx: kebab-case | PascalCase
  .d.ts: kebab-case

  backend:
    .ts: regex:([.a-z0-9]*)([-.][a-z0-9]+)*

ignore:
  - .git
  - node_modules
  - commitlint.config.ts
  - client/vite.config.ts
  - backend/test
  - backend/node_modules
  - client/node_modules
  - backend/dist
