name: Linting project

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: |
          npm install

      - name: Install Dependencies (Client folder)
        working-directory: client
        run: |
          npm install

      - name: Install Dependencies (Backend folder)
        working-directory: backend
        run: |
          npm install

      - name: Prisma Generate
        working-directory: backend
        run: |
          npx prisma generate

      - name: Code Linting
        run: |
          npm run lint:all
